// Copyright 2026 Ayesh Almeida
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const snapshotHeader = "# lib-disruptor exported API\n# Generated by cmd/apicheck; do not edit manually.\n\n"

type packageSource struct {
	fileSet *token.FileSet
	files   []*ast.File
	defs    map[*ast.Ident]types.Object
}

func main() {
	directory := flag.String("dir", ".", "package directory to inspect")
	check := flag.String("check", "", "compare the generated API with this snapshot")
	flag.Parse()

	output, err := snapshot(*directory)
	if err != nil {
		fail(err)
	}
	if *check == "" {
		fmt.Print(output)
		return
	}

	expected, err := os.ReadFile(*check)
	if err != nil {
		fail(err)
	}
	if !bytes.Equal(expected, []byte(output)) {
		fmt.Fprintf(os.Stderr, "exported API differs from %s; review the API change and update the baseline intentionally\n", *check)
		os.Exit(1)
	}
}

func snapshot(directory string) (string, error) {
	source, err := loadPackage(directory)
	if err != nil {
		return "", err
	}
	entries := make([]string, 0)
	for _, file := range source.files {
		for _, declaration := range file.Decls {
			switch declaration := declaration.(type) {
			case *ast.GenDecl:
				entries = append(entries, declarationEntries(source, declaration)...)
			case *ast.FuncDecl:
				if declaration.Name.IsExported() && (declaration.Recv == nil || exportedReceiver(declaration.Recv)) {
					entries = append(entries, renderFunc(source.fileSet, declaration))
				}
			}
		}
	}
	sort.Strings(entries)
	return snapshotHeader + strings.Join(entries, "\n") + "\n", nil
}

func loadPackage(directory string) (*packageSource, error) {
	fileSet := token.NewFileSet()
	files, err := os.ReadDir(directory)
	if err != nil {
		return nil, err
	}
	parsed := make([]*ast.File, 0)
	for _, file := range files {
		if file.IsDir() || !strings.HasSuffix(file.Name(), ".go") || strings.HasSuffix(file.Name(), "_test.go") {
			continue
		}
		tree, err := parser.ParseFile(fileSet, filepath.Join(directory, file.Name()), nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		parsed = append(parsed, tree)
	}
	if len(parsed) == 0 {
		return nil, fmt.Errorf("no Go source files found in %s", directory)
	}

	defs := make(map[*ast.Ident]types.Object)
	config := types.Config{Importer: importer.Default()}
	if _, err := config.Check(parsed[0].Name.Name, fileSet, parsed, &types.Info{Defs: defs}); err != nil {
		return nil, err
	}
	return &packageSource{fileSet: fileSet, files: parsed, defs: defs}, nil
}

func declarationEntries(source *packageSource, declaration *ast.GenDecl) []string {
	entries := make([]string, 0)
	for _, specification := range declaration.Specs {
		switch specification := specification.(type) {
		case *ast.TypeSpec:
			if specification.Name.IsExported() {
				entries = append(entries, renderType(source.fileSet, specification))
			}
		case *ast.ValueSpec:
			for _, name := range specification.Names {
				if !name.IsExported() {
					continue
				}
				entry := declaration.Tok.String() + " " + name.Name
				if object := source.defs[name]; object != nil && object.Type() != nil {
					entry += " " + publicTypeString(object.Type(), source.files[0].Name.Name)
					if constantObject, ok := object.(*types.Const); ok {
						entry += " = " + constantObject.Val().String()
					}
				}
				entries = append(entries, entry)
			}
		}
	}
	return entries
}

func renderType(fileSet *token.FileSet, specification *ast.TypeSpec) string {
	prefix := "type " + specification.Name.Name
	if specification.TypeParams != nil {
		prefix += renderFieldList(fileSet, specification.TypeParams)
	}
	switch underlying := specification.Type.(type) {
	case *ast.StructType:
		return prefix + " " + renderPublicStruct(fileSet, underlying)
	case *ast.InterfaceType:
		return prefix + " " + renderPublicInterface(fileSet, underlying)
	default:
		return prefix + " " + renderNode(fileSet, specification.Type)
	}
}

func renderFieldList(fileSet *token.FileSet, fields *ast.FieldList) string {
	parts := make([]string, 0, len(fields.List))
	for _, field := range fields.List {
		copy := *field
		copy.Doc = nil
		copy.Comment = nil
		parts = append(parts, renderField(fileSet, &copy))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func renderPublicStruct(fileSet *token.FileSet, structure *ast.StructType) string {
	fields := make([]string, 0)
	hasUnexported := false
	for _, field := range structure.Fields.List {
		names := make([]*ast.Ident, 0, len(field.Names))
		for _, name := range field.Names {
			if name.IsExported() {
				names = append(names, name)
			} else {
				hasUnexported = true
			}
		}
		if len(field.Names) == 0 {
			if embeddedExported(field.Type) {
				names = field.Names
			} else {
				hasUnexported = true
			}
		}
		if len(names) == 0 {
			continue
		}
		copy := *field
		copy.Doc = nil
		copy.Comment = nil
		copy.Names = names
		fields = append(fields, "\t"+renderField(fileSet, &copy))
	}
	if hasUnexported {
		fields = append(fields, "\t// unexported fields")
	}
	return "struct {\n" + strings.Join(fields, "\n") + "\n}"
}

func renderPublicInterface(fileSet *token.FileSet, interfaceType *ast.InterfaceType) string {
	methods := make([]string, 0)
	hasUnexported := false
	for _, field := range interfaceType.Methods.List {
		if len(field.Names) == 0 {
			if embeddedExported(field.Type) {
				methods = append(methods, "\t"+renderField(fileSet, field))
			} else {
				hasUnexported = true
			}
			continue
		}
		names := make([]*ast.Ident, 0, len(field.Names))
		for _, name := range field.Names {
			if name.IsExported() {
				names = append(names, name)
			} else {
				hasUnexported = true
			}
		}
		if len(names) == 0 {
			continue
		}
		copy := *field
		copy.Doc = nil
		copy.Comment = nil
		copy.Names = names
		methods = append(methods, "\t"+renderField(fileSet, &copy))
	}
	if hasUnexported {
		methods = append(methods, "\t// unexported methods")
	}
	return "interface {\n" + strings.Join(methods, "\n") + "\n}"
}

func renderFunc(fileSet *token.FileSet, declaration *ast.FuncDecl) string {
	copy := *declaration
	copy.Doc = nil
	copy.Body = nil
	return renderNode(fileSet, &copy)
}

func exportedReceiver(fieldList *ast.FieldList) bool {
	if len(fieldList.List) != 1 {
		return false
	}
	return embeddedExported(fieldList.List[0].Type)
}

func embeddedExported(expression ast.Expr) bool {
	switch expression := expression.(type) {
	case *ast.Ident:
		return expression.IsExported()
	case *ast.StarExpr:
		return embeddedExported(expression.X)
	case *ast.IndexExpr:
		return embeddedExported(expression.X)
	case *ast.IndexListExpr:
		return embeddedExported(expression.X)
	case *ast.SelectorExpr:
		return expression.Sel.IsExported()
	default:
		return false
	}
}

func publicTypeString(typ types.Type, packageName string) string {
	text := types.TypeString(typ, func(pkg *types.Package) string {
		if pkg.Name() == packageName {
			return ""
		}
		return pkg.Name()
	})
	return strings.TrimPrefix(text, ".")
}

func renderField(fileSet *token.FileSet, field *ast.Field) string {
	structure := &ast.StructType{Fields: &ast.FieldList{List: []*ast.Field{field}}}
	text := renderNode(fileSet, structure)
	text = strings.TrimPrefix(text, "struct {")
	text = strings.TrimSuffix(text, "}")
	return strings.TrimSpace(text)
}

func renderNode(fileSet *token.FileSet, node ast.Node) string {
	var output bytes.Buffer
	if err := format.Node(&output, fileSet, node); err != nil {
		fail(err)
	}
	return strings.TrimSpace(output.String())
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
